const ActionType = {
  CONNECT_REQUEST: 'CONNECT_REQUEST',
  CONNECT_SUCCESS: 'CONNECT_SUCCESS',
  DISCONNECT_REQUEST: 'DISCONNECT_REQUEST',
  DISCONNECT_SUCCESS: 'DISCONNECT_SUCCESS',
};

export default ActionType;
